apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
    tier: front
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: vote
spec:
  ports:
  - name: "80"
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
