apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 7
images:
- name: schoolofdevops/vote
  newName: januszkujawa84/vote
  newTag: main-b4f3a37d-1645471725 #{"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "k8s-sre@example.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
